### ISSUE TITLE
Link has failed.

### ISSUE THREAD

**Issue by zhanjiahui** [dobrosketchkun/NeuralKuvshinov_v2#2]
Thank you for your wonderful work.

However, the link of v2.1/v2.2/v2.3 were failed. So I had to downland checkpoint of v1.27 and generate images use stylegan2 model.
Here are images i generated used v1.27, and it looks like corrupted images. Could you please tell me how to download checkpoints of V2 version to generate normal images?

![图片](https://user-images.githubusercontent.com/36075322/231212890-4e4de1dd-8cad-4888-a249-7fb498670356.png)

Thanks a million again.

**Comment by dobrosketchkun** [comment]
Yeah, try [these ones](https://mega.nz/folder/eNdXQAzB#Slq50L_kwvQT21RxukpuIg), I kind of relocated everything from my google drive (for reasons), and since everybody is on SD and MJ right now I kind of forget about StyleGANS and such

**Comment by zhanjiahui** [comment]
Thank you for your reply !
